#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
MURNET BUILD SCRIPT v6.1
Produces two standalone executables via PyInstaller:

  dist/murnet-cli       — headless CLI node
  dist/murnet-desktop   — GUI desktop application

Usage (open / dev mode — no network secret):
    pip install pyinstaller
    python build_exe.py [--target cli|desktop|all] [--onedir] [--clean]

Usage (private / authorized network — secret injected into binary):
    # Linux / macOS:
    export MURNET_SECRET=<64-char hex string>
    python build_exe.py --target all

    # Windows:
    set MURNET_SECRET=<64-char hex string>
    python build_exe.py --target all

The MURNET_SECRET is written into a temporary PyInstaller runtime hook and
bundled into the binary — it is NEVER written to disk in plaintext outside
of the build/ work directory, which you should exclude from version control.

The script auto-detects Windows (.exe) vs POSIX (no extension).
"""

import argparse
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

ROOT      = Path(__file__).parent.resolve()
DIST_DIR  = ROOT / "dist"
BUILD_DIR = ROOT / "build"
ICON_DIR  = ROOT / "assets" / "icons"

IS_WINDOWS = platform.system() == "Windows"
IS_MACOS   = platform.system() == "Darwin"
EXE_SUFFIX = ".exe" if IS_WINDOWS else ""

# Runtime hook written at build time and deleted afterwards
_SECRET_HOOK_PATH = BUILD_DIR / "_murnet_secret_hook.py"

# ---------------------------------------------------------------------------
# Hidden imports required by cryptography / asyncio / tkinter on some
# platforms that PyInstaller's analysis misses.
# ---------------------------------------------------------------------------
HIDDEN_IMPORTS = [
    "cryptography.hazmat.primitives.asymmetric.ed25519",
    "cryptography.hazmat.primitives.asymmetric.x25519",
    "cryptography.hazmat.primitives.kdf.hkdf",
    "cryptography.hazmat.primitives.ciphers.aead",
    "cryptography.hazmat.backends.openssl.backend",
    "asyncio.selector_events",
    "asyncio.proactor_events",
    "uvicorn.logging",
    "uvicorn.loops.auto",
    "uvicorn.protocols.http.auto",
    "uvicorn.lifespan.on",
    "fastapi",
    "pydantic",
    "puremagic",
    "rich",
    "prompt_toolkit",
    "tkinter",
    "tkinter.ttk",
    "tkinter.scrolledtext",
    "sqlite3",
    "pyyaml",
    "jwt",
    "psutil",
    # core — updated paths after restructure
    "core.net.transport",
    "core.net.async_transport",
    "core.net.routing",
    "core.net.dht_rpc",
    "core.net.murnaked",
    "core.net.protocol",
    "core.net.network_auth",
    "core.identity.crypto",
    "core.identity.identity",
    "core.identity.keystore",
    "core.data.storage",
    "core.data.objects",
    "core.data.migrations",
    "core.node.node",
    "core.node.async_node",
    "core.node.pubsub",
    "core.integrity",
    "core.config",
    # API / mobile
    "api.server",
    "api.models",
    "api.auth",
    "mobile.battery",
    "mobile.network",
    "mobile.sync",
]

# ---------------------------------------------------------------------------
# Data files to bundle (relative to ROOT)
# ---------------------------------------------------------------------------
DATA_FILES = []

for docs_file in (ROOT / "docs").glob("*.md"):
    DATA_FILES.append((str(docs_file), "docs"))

readme = ROOT / "README.md"
if readme.exists():
    DATA_FILES.append((str(readme), "."))


# ---------------------------------------------------------------------------
# Secret injection via PyInstaller runtime hook
# ---------------------------------------------------------------------------

def _write_secret_hook() -> "Path | None":
    """
    If MURNET_SECRET is set in the environment, write a PyInstaller runtime
    hook that injects the secret into core.net.network_auth at binary startup.
    Returns the hook path, or None when building in open mode.
    """
    secret_hex = os.environ.get("MURNET_SECRET", "").strip()
    if not secret_hex:
        print(
            "[build] MURNET_SECRET not set — building in open mode "
            "(no network authentication)."
        )
        return None

    try:
        secret_bytes = bytes.fromhex(secret_hex)
    except ValueError:
        print("[build] ERROR: MURNET_SECRET is not valid hex — aborting.")
        sys.exit(1)

    if len(secret_bytes) < 16:
        print("[build] ERROR: MURNET_SECRET must be at least 16 bytes (32 hex chars).")
        sys.exit(1)

    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    hook_code = (
        "# Auto-generated by build_exe.py — injected at build time.\n"
        "# Contains the network secret — keep build/ out of version control.\n"
        "def _inject_secret():\n"
        "    import core.net.network_auth as _na\n"
        f"    _na.set_secret(bytes.fromhex('{secret_hex}'))\n"
        "_inject_secret()\n"
    )
    _SECRET_HOOK_PATH.write_text(hook_code, encoding="utf-8")
    print(
        f"[build] Network secret injected ({len(secret_bytes)} bytes) "
        "via runtime hook."
    )
    return _SECRET_HOOK_PATH


def _remove_secret_hook() -> None:
    """Delete the temporary runtime hook file."""
    if _SECRET_HOOK_PATH.exists():
        _SECRET_HOOK_PATH.unlink()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _find_icon(name: str) -> "str | None":
    """Return path to icon file for the current platform, or None."""
    ICON_DIR.mkdir(parents=True, exist_ok=True)
    if IS_WINDOWS:
        ico = ICON_DIR / f"{name}.ico"
        return str(ico) if ico.exists() else None
    if IS_MACOS:
        icns = ICON_DIR / f"{name}.icns"
        return str(icns) if icns.exists() else None
    png = ICON_DIR / f"{name}.png"
    return str(png) if png.exists() else None


def _build_args(
    script: Path,
    name: str,
    onefile: bool = True,
    console: bool = True,
    icon: "str | None" = None,
    secret_hook: "Path | None" = None,
) -> list:
    """Compose pyinstaller command-line arguments."""
    args = [
        sys.executable, "-m", "PyInstaller",
        str(script),
        "--name", name,
        "--distpath", str(DIST_DIR),
        "--workpath", str(BUILD_DIR),
        "--specpath", str(BUILD_DIR),
        "--noconfirm",
    ]

    if onefile:
        args.append("--onefile")
    else:
        args.append("--onedir")

    if not console:
        args.append("--windowed")     # no console window (GUI)

    if icon:
        args += ["--icon", icon]

    if secret_hook:
        args += ["--runtime-hook", str(secret_hook)]

    # Hidden imports
    for hi in HIDDEN_IMPORTS:
        args += ["--hidden-import", hi]

    # Data files
    sep = ";" if IS_WINDOWS else ":"
    for src, dst in DATA_FILES:
        args += ["--add-data", f"{src}{sep}{dst}"]

    # UPX compression (if available)
    if shutil.which("upx"):
        args.append("--upx-dir=" + shutil.which("upx").rsplit(os.sep, 1)[0])

    return args


def build_cli(onefile: bool, secret_hook: "Path | None"):
    script = ROOT / "cli.py"
    name   = "murnet-cli"
    icon   = _find_icon("murnet-cli")
    args   = _build_args(script, name, onefile=onefile, console=True, icon=icon,
                         secret_hook=secret_hook)

    print(f"\n[build] Building CLI: {name}{EXE_SUFFIX}")
    result = subprocess.run(args, cwd=ROOT)
    if result.returncode != 0:
        print(f"[build] FAILED (exit code {result.returncode})")
        return False
    print(f"[build] OK -> dist/{name}{EXE_SUFFIX}")
    return True


def build_desktop(onefile: bool, secret_hook: "Path | None"):
    script = ROOT / "desktop_app.py"
    name   = "murnet-desktop"
    icon   = _find_icon("murnet-desktop")
    args   = _build_args(script, name, onefile=onefile, console=not IS_WINDOWS,
                         icon=icon, secret_hook=secret_hook)
    if IS_WINDOWS:
        args.append("--windowed")

    print(f"\n[build] Building Desktop: {name}{EXE_SUFFIX}")
    result = subprocess.run(args, cwd=ROOT)
    if result.returncode != 0:
        print(f"[build] FAILED (exit code {result.returncode})")
        return False
    print(f"[build] OK -> dist/{name}{EXE_SUFFIX}")
    return True


def clean():
    for d in (DIST_DIR, BUILD_DIR):
        if d.exists():
            shutil.rmtree(d)
            print(f"[clean] Removed {d}")
    for spec in ROOT.glob("*.spec"):
        spec.unlink()
        print(f"[clean] Removed {spec}")


def check_pyinstaller():
    try:
        import PyInstaller  # noqa: F401
        return True
    except ImportError:
        print("[error] PyInstaller not found. Install with: pip install pyinstaller")
        return False


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(
        prog="build_exe",
        description="Build Murnet executables with PyInstaller",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("--target",  choices=["cli", "desktop", "all"], default="all",
                   help="Which executable to build (default: all)")
    p.add_argument("--onedir",  action="store_true",
                   help="Use --onedir instead of --onefile (faster startup)")
    p.add_argument("--clean",   action="store_true",
                   help="Clean build artefacts before building")
    args = p.parse_args()

    if args.clean:
        clean()

    if not check_pyinstaller():
        sys.exit(1)

    onefile     = not args.onedir
    secret_hook = _write_secret_hook()

    ok = True
    try:
        if args.target in ("cli", "all"):
            ok &= build_cli(onefile=onefile, secret_hook=secret_hook)

        if args.target in ("desktop", "all"):
            ok &= build_desktop(onefile=onefile, secret_hook=secret_hook)
    finally:
        _remove_secret_hook()

    if ok:
        mode = "authorized" if secret_hook else "open"
        print(f"\n[build] All done ({mode} mode). Executables in {DIST_DIR}/")
        print(f"  murnet-cli{EXE_SUFFIX}     — headless CLI node")
        print(f"  murnet-desktop{EXE_SUFFIX} — GUI application")
    else:
        print("\n[build] One or more builds FAILED.")
        sys.exit(1)


if __name__ == "__main__":
    main()
