#!/usr/bin/env python3
"""
Murnet Config Generator
Generates a default config.yaml for VDS deployment.

Usage:
    python scripts/generate_config.py [--output PATH] [--non-interactive]
"""
import argparse
import os
import secrets
import sys


def _yaml_str(value: str) -> str:
    need_quotes = any(c in value for c in ':{}[]|>&*!,#\'"')
    if need_quotes or not value:
        escaped = value.replace("'", "''")
        return f"'{escaped}'"
    return value


def _yaml_list(items: list, indent: int = 2) -> str:
    if not items:
        return "[]"
    pad = " " * indent
    lines = "\n"
    for item in items:
        lines += f"{pad}- {_yaml_str(str(item))}\n"
    return lines.rstrip("\n")


def render_config(cfg: dict) -> str:
    n  = cfg["network"]
    st = cfg["storage"]
    dh = cfg["dht"]
    ap = cfg["api"]
    sc = cfg["security"]
    vd = cfg["vds"]

    def yn(b: bool) -> str:
        return "true" if b else "false"

    return f"""\
# Murnet VDS Configuration v6.0
# Generated by scripts/generate_config.py
# Edit as needed then place at /etc/murnet/config.yaml

log_level: {_yaml_str(cfg['log_level'])}
debug: {yn(cfg['debug'])}

network:
  bind_host: {_yaml_str(n['bind_host'])}
  port: {n['port']}
  nat_traversal: {yn(n['nat_traversal'])}
  upnp_enabled: {yn(n['upnp_enabled'])}
  bootstrap_nodes: {_yaml_list(n['bootstrap_nodes'])}

storage:
  data_dir: {_yaml_str(st['data_dir'])}
  max_size_mb: {st['max_size_mb']}
  compression: {yn(st['compression'])}
  wal_mode: {yn(st['wal_mode'])}
  auto_vacuum: {yn(st['auto_vacuum'])}

dht:
  replication_factor: {dh['replication_factor']}
  ttl_default: {dh['ttl_default']}

api:
  enabled: {yn(ap['enabled'])}
  host: {_yaml_str(ap['host'])}
  port: {ap['port']}
  jwt_secret: {_yaml_str(ap['jwt_secret'])}
  jwt_expire_hours: {ap['jwt_expire_hours']}
  cors_origins: {_yaml_list(ap['cors_origins'])}

security:
  require_auth: {yn(sc['require_auth'])}
  rate_limit_requests: {sc['rate_limit_requests']}
  rate_limit_window: {sc['rate_limit_window']}
  encryption_at_rest: {yn(sc['encryption_at_rest'])}

vds:
  systemd_integration: {yn(vd['systemd_integration'])}
  monitoring_enabled: {yn(vd['monitoring_enabled'])}
  log_rotation: {yn(vd['log_rotation'])}
  max_log_size_mb: {vd['max_log_size_mb']}
  max_log_files: {vd['max_log_files']}
"""


def _prompt(msg: str, default: str, validator=None) -> str:
    while True:
        try:
            raw = input(f"  {msg} [{default}]: ").strip()
        except EOFError:
            raw = ""
        value = raw if raw else default
        if validator:
            try:
                validator(value)
            except ValueError as exc:
                print(f"    Invalid: {exc}. Try again.")
                continue
        return value


def _validate_port(value: str) -> int:
    n = int(value)
    if not (1 <= n <= 65535):
        raise ValueError(f"Port must be 1-65535, got {n}")
    return n


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a default config.yaml for Murnet VDS deployment."
    )
    parser.add_argument("--output", "-o", default=None, metavar="PATH",
                        help="Write config to this file (default: stdout)")
    parser.add_argument("--non-interactive", "-n", action="store_true",
                        help="Use all defaults without prompting")
    args = parser.parse_args()

    interactive = not args.non_interactive and sys.stdin.isatty()

    if interactive:
        print("\nMurnet Config Generator v6.0")
        print("Press Enter to accept the default shown in [brackets].\n")
        bind_port_str = _prompt("P2P bind port", "8888", _validate_port)
        api_port_str  = _prompt("API port",      "8080", _validate_port)
        data_dir      = _prompt("Data directory", "/var/lib/murnet")
        api_host      = _prompt("API listen host", "0.0.0.0")
        max_storage   = _prompt("Max storage MB", "2000")
    else:
        bind_port_str = "8888"
        api_port_str  = "8080"
        data_dir      = "/var/lib/murnet"
        api_host      = "0.0.0.0"
        max_storage   = "2000"

    jwt_secret = secrets.token_hex(32)

    cfg = {
        "log_level": "INFO",
        "debug": False,
        "network": {
            "bind_host": "0.0.0.0",
            "port": int(bind_port_str),
            "nat_traversal": True,
            "upnp_enabled": False,
            "bootstrap_nodes": [],
        },
        "storage": {
            "data_dir": data_dir,
            "max_size_mb": int(max_storage),
            "compression": True,
            "wal_mode": True,
            "auto_vacuum": True,
        },
        "dht": {
            "replication_factor": 5,
            "ttl_default": 86400,
        },
        "api": {
            "enabled": True,
            "host": api_host,
            "port": int(api_port_str),
            "jwt_secret": jwt_secret,
            "jwt_expire_hours": 24,
            "cors_origins": ["*"],
        },
        "security": {
            "require_auth": True,
            "rate_limit_requests": 100,
            "rate_limit_window": 60,
            "encryption_at_rest": True,
        },
        "vds": {
            "systemd_integration": True,
            "monitoring_enabled": True,
            "log_rotation": True,
            "max_log_size_mb": 100,
            "max_log_files": 5,
        },
    }

    yaml_text = render_config(cfg)

    if args.output:
        os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
        with open(args.output, "w") as fh:
            fh.write(yaml_text)
        print(f"Config written to: {args.output}")
        print(f"  P2P port  : {cfg['network']['port']}")
        print(f"  API port  : {cfg['api']['port']}")
        print(f"  Data dir  : {cfg['storage']['data_dir']}")
        print(f"  JWT secret: {jwt_secret[:8]}...  (keep this secret!)")
    else:
        sys.stdout.write(yaml_text)

    return 0


if __name__ == "__main__":
    sys.exit(main())
